### ISSUE TITLE
Includes hidden rows in validation

### ISSUE THREAD

**Issue by JJLewis** [demetrio812/EurekaSwiftValidatorComponents#2]
So if I have some hidden rows in a table that do not need to be there, but they happen to be textfields.
EurekaSwiftValidatorComponents includes that in the validation, so that the form actually does not get validated unless those hidden field fulfil their rules.

**Comment by demetrio812** [comment]
Hello, this should be fixed now, please try it and let me know, I've also updated the example project to test the hidden fields.
