### ISSUE TITLE
How to have a valid password field with secure text ?

### ISSUE THREAD

**Issue by ins0u** [demetrio812/EurekaSwiftValidatorComponents#3]
Hello,

I just found this library and it works perfectly with Eureka (thanks for your work ^^)

But I have an issue with a password field.
How to manage the password field so that it keeps hidden characters (black spots)?

In my code, I have

```
<<< PasswordRow("Password"){
     $0.title = "password"
}
```

and there isn't SVPasswordRow in this library..
How to add it ?
Or maybe we can add a textfield (SvTextRow) and add a parameter to secure the text that is entered ?

Thanks for your help :)

(Sorry for my bad English :/)

**Comment by skrosoft** [comment]
I was looking for the same funcionality ... so I have forked the project and developped it.

https://github.com/skrosoft/EurekaSwiftValidatorComponents

You can now use SVPasswordRow.

I'm now looking to do a SVDateRow extending DateRow ... after that, my form will be finished.

@ins0u @demetrio812  any idea on how to do the same with the Eureka DateRow field?

**Comment by demetrio812** [comment]
Hello @ins0u @skrosoft, just pushed the new version, @skrosoft please note that adding the component is not enough, I had to fix the validate() function in order to consider not only SVTextRow

For the date row I guess it's the same, I will look at it in the next days, in the meantime, I'm happy to review a pull request :)

**Comment by skrosoft** [comment]
Hi @demetrio812, wish you are fine. Have you looked at the SVDateRow and the validate() function?

**Comment by skrosoft** [comment]
Hi @demetrio812 , wish you are fine. Have you looked at the SVDateRow and the validate() function?
